name: Daily Security Alert Check

on:
  schedule:
    - cron: '0 1 * * *'     # daily at 01:00 UTC (adjust as needed)
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  security-events: read

env:
  REPO: ${{ github.repository }}
  OWNER: ${{ github.repository_owner }}

jobs:
  check_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for CLI)
        uses: actions/checkout@v4

      - name: Install GitHub CLI & jq
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Login GH CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch Dependabot alerts
        id: dependabot
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${OWNER}/${{ github.event.repository.name }}/dependabot/alerts?state=open \
            > dependabot_alerts.json || echo "[]">dependabot_alerts.json
          COUNT_DB=$(jq length < dependabot_alerts.json)
          echo "DB_COUNT=${COUNT_DB}" >> $GITHUB_ENV

      - name: Fetch CodeScanning alerts
        id: codescan
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${OWNER}/${{ github.event.repository.name }}/code-scanning/alerts?state=open \
            > codescan_alerts.json || echo "[]">codescan_alerts.json
          COUNT_CS=$(jq length < codescan_alerts.json)
          echo "CS_COUNT=${COUNT_CS}" >> $GITHUB_ENV

      - name: Fetch SecretScanning alerts
        id: secretscan
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${OWNER}/${{ github.event.repository.name }}/secret-scanning/alerts?state=open \
            > secretscan_alerts.json || echo "[]">secretscan_alerts.json
          COUNT_SS=$(jq length < secretscan_alerts.json)
          echo "SS_COUNT=${COUNT_SS}" >> $GITHUB_ENV

      - name: Create issue if any alerts found
        if: ${{ env.DB_COUNT != '0' || env.CS_COUNT != '0' || env.SS_COUNT != '0' }}
        run: |
          ISSUE_TITLE="🔒 Security Alerts Summary for ${REPO}"
          {
            echo "### Summary"
            echo "- Dependabot alerts: ${DB_COUNT}"
            echo "- Code Scanning alerts: ${CS_COUNT}"
            echo "- Secret Scanning alerts: ${SS_COUNT}"
            echo
            echo "### Dependabot (open alerts)"
            jq . < dependabot_alerts.json
            echo
            echo "### Code Scanning (open alerts)"
            jq . < codescan_alerts.json
            echo
            echo "### Secret Scanning (open alerts)"
            jq . < secretscan_alerts.json
          } > full_alert_report.md

          gh api \
            --method POST \
            repos/${OWNER}/${{ github.event.repository.name }}/issues \
            -f title="${ISSUE_TITLE}" \
            -f body@"full_alert_report.md"

      - name: No alerts found
        if: ${{ env.DB_COUNT == '0' && env.CS_COUNT == '0' && env.SS_COUNT == '0' }}
        run: |
          echo "No open alerts across Dependabot/CodeScanning/SecretScanning for ${REPO}."

